### ISSUE TITLE
Python whl package build on raspberry4b failed.

### ISSUE THREAD

**Issue by zoldaten** [MegEngine/MegEngine#472] opened 2022-07-30 11:33 UTC
hello.

i tried to build python wheel on raspberry pi:
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
bullseye raspbian 64 os.

following instructions ([link](https://github.com/MegEngine/MegEngine/blob/master/scripts/whl/BUILD_PYTHON_WHL_README.md)) i`ve built docker image(it took 10 hours on pi):
REPOSITORY                               TAG                  IMAGE ID           CREATED                  SIZE
env_manylinux2014                    latest               686b6ee5537e   About an hour ago   3.04GB

Then i execute:
`./scripts/whl/manylinux2014/build_wheel_common.sh -sdk cpu`

and got permission errors like that:
```
rm: cannot remove ‘/home/code/build_dir/host/MGE_WITH_CUDA_OFF/MGE_INFERENCE_ONLY_OFF/Release/build/flatbuffers/flatc’: Permission denied
rm: cannot remove ‘/home/code/build_dir/host/MGE_WITH_CUDA_OFF/MGE_INFERENCE_ONLY_OFF/Release/build/flatbuffers/libflatbuffers.a’: Permission denied
rm: cannot remove ‘/home/code/build_dir/host/MGE_WITH_CUDA_OFF/MGE_INFERENCE_ONLY_OFF/Release/build/genfiles/megbrain_build_config.h’: Permission denied
rm: cannot remove ‘/home/code/build_dir/host/MGE_WITH_CUDA_OFF/MGE_INFERENCE_ONLY_OFF/Release/build/genfiles/git_full_hash_header.h’: Permission denied
rm: cannot remove 
```
As far as i understand errors from docker image. How to fix that ? Perhaps change permissions somehow in docker image ?

**Comment by haolongzhangm** [comment] 2022-07-30 12:07
@zoldaten     congratulation， when success build docker image, you already do 50% of build the whl package 

now you got the permission, i think caused by two reason, 
* you call ./scripts/cmake-build/host_build.sh before call ./scripts/whl/manylinux2014/build_wheel_common.sh ?
* you docker may have strict config of permission

but I think you can ''reslove the permission issue" by:
git clean -xdf && git reset --hard && ./scripts/whl/manylinux2014/build_wheel_common.sh -sdk cpu

**Comment by zoldaten** [comment] 2022-07-31 17:10
@haolongzhangm i tried:
git clean -xdf && git reset --hard && ./scripts/whl/manylinux2014/build_wheel_common.sh -sdk cpu
waste all space on sd-card (32Gb) and move to 64Gb.
But build was unsuccess:
```
../../../../../../lite/example/cpp_example/mge/cv/stb_image.h:1124:14: warning: ‘void stbi_set_flip_vertically_on_load(int)’ defined but not used [-Wunused-function]
 STBIDEF void stbi_set_flip_vertically_on_load(int flag_true_if_should_flip) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../lite/example/cpp_example/mge/cv/stb_image.h:1000:21: warning: ‘const char* stbi_failure_reason()’ defined but not used [-Wunused-function]
 STBIDEF const char* stbi_failure_reason(void) {
                     ^~~~~~~~~~~~~~~~~~~
[1296/1304] Linking CXX executable lite/example/cpp_example/lite_examples
FAILED: lite/example/cpp_example/lite_examples 
: && /opt/rh/devtoolset-8/root/usr/bin/c++ -include /home/code/src/bin_reduce_cmake.h -ffunction-sections -fdata-sections -Wall -Wextra -march=armv8-a -fvisibility=hidden -g -O3 -DNDEBUG -fno-finite-math-only -Wl,--gc-sections -flto=full -fuse-ld=gold lite/example/cpp_example/CMakeFiles/lite_examples.dir/main.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/basic.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/cpu_affinity.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/cv/detect_yolox.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/cv/picture_classification.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/device_io.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/lite_c_interface.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/network_share_weights.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/reset_io.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/user_allocator.cpp.o lite/example/cpp_example/CMakeFiles/lite_examples.dir/mge/user_cryption.cpp.o -o lite/example/cpp_example/lite_examples  lite/liblite_static.a  -ldl  -lrt  -ldl  -lrt  flatbuffers/libflatbuffers.a  -latomic  dnn/atlas-stub/libatlas-stub.a  cpuinfo/libcpuinfo.a  cpuinfo/deps/clog/libclog.a  -pthread && :
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
[1300/1304] Linking CXX static library lite/liblite_static_all_in_one.a
ninja: build stopped: subcommand failed.
```
1300 of 1304 ...i was almost there (

`./scripts/cmake-build/host_build.sh` build failed either ((

**Comment by haolongzhangm** [comment] 2022-08-01 01:20
ld terminated with signal 9 [Killed]    means  out of memory

* you can do: dmesg      to get system kill ld
* DDR size is ?  may you need create a swap zone if you DDR size is low

**Comment by haolongzhangm** [comment] 2022-08-01 01:47
all you can limit the ld  thread number  by patch
```
diff --git a/scripts/cmake-build/utils/utils.sh b/scripts/cmake-build/utils/utils.sh
index fc52bdc638..0ebcbef2d9 100755
--- a/scripts/cmake-build/utils/utils.sh
+++ b/scripts/cmake-build/utils/utils.sh
@@ -136,5 +136,6 @@ function config_ninja_default_max_jobs() {
     else
         ((NINJA_MAX_JOBS = ${cpu_number} + 2))
     fi
+    NINJA_MAX_JOBS=1
     echo "config default NINJA_MAX_JOBS to ${NINJA_MAX_JOBS} [cpu number is:${cpu_number}]"
 }
diff --git a/scripts/whl/manylinux2014/do_build_common.sh b/scripts/whl/manylinux2014/do_build_common.sh
index 5e2f863201..938927b1e7 100755
--- a/scripts/whl/manylinux2014/do_build_common.sh
+++ b/scripts/whl/manylinux2014/do_build_common.sh
@@ -113,7 +113,7 @@ do
         # TODO: may all cmake issue can be resolved after rm CMakeCache?
         # if YES, remove this to use old cache and speed up CI
         echo "warning: remove old build_dir for the first loop"
-        rm -rf ${BUILD_DIR}
+        #rm -rf ${BUILD_DIR}
     fi
 
     python_ver=`echo $ver | tr -d m`

```

**Comment by zoldaten** [comment] 2022-08-01 11:52
thats right. that was a memory issue. I made a swap 5Gb (8Gb on my raspberry pi already).
Now i have wheels! Ive installed with pip.
And tried to convert:
`python3 tools/export_mge.py -n yolox-tiny -c yolox_tiny.pkl --dump_path yolox_tiny.mge`

But got the error:
```
Traceback (most recent call last):
  File "/home/pi/YOLOX/tools/export_mge.py", line 66, in <module>
    main(args, exp)
  File "/home/pi/YOLOX/tools/export_mge.py", line 59, in main
    model = build_and_load(model, exp)
  File "/home/pi/YOLOX/tools/export_mge.py", line 49, in build_and_load
    model_weights = mge.load(weight_file)
  File "/home/pi/.local/lib/python3.9/site-packages/megengine/serialization.py", line 105, in load
    return pickle_module.load(f)
TypeError: file must have 'read' and 'readline' attributes
```
I think that is something wrong with pickle. How to fix it ? 

Also i have strange result with boxex around objects on picture with python example:
python tools/demo.py image -n yolox-tiny -c models/yolox_tiny.pkl --path assets/dog.jpg --conf 0.25 --nms 0.45 --tsize 256 --save_result

boxes are out of the objects.

**Comment by haolongzhangm** [comment] 2022-08-02 02:54
@zoldaten  Hi
1: cd YOLOX  ; git pull 
you show see the latest commit
```
commit 9e17c5d6beeedfa0544d24787a5f3383eebfae66 (HEAD -> main, origin/main, origin/HEAD)
Author: haolongzhangm <longhaozhang@gmail.com>
Date:   Tue Aug 2 10:46:47 2022 +0800

    fix(tools): load bug in export_mge (#10)
    
    fix(tools): load bug in export_mge

```

2:  download "yolox_tiny.pkl"  from https://github.com/MegEngine/YOLOX

3:  then run you command again

**Comment by zoldaten** [comment] 2022-08-02 04:41
Now a got this one:
```
Traceback (most recent call last):
  File "/home/pi/YOLOX/tools/export_mge.py", line 66, in <module>
    main(args, exp)
  File "/home/pi/YOLOX/tools/export_mge.py", line 59, in main
    model = build_and_load(model, args.ckpt)
  File "/home/pi/YOLOX/tools/export_mge.py", line 50, in build_and_load
    model.load_state_dict(model_weights, strict=False)
  File "/home/pi/.local/lib/python3.9/site-packages/megengine/module/module.py", line 550, in load_state_dict
    loaded, skipped = self._load_state_dict_with_closure(closure)
  File "/home/pi/.local/lib/python3.9/site-packages/megengine/module/module.py", line 604, in _load_state_dict_with_closure
    raise ValueError(
ValueError: param `backbone.C3_n3.conv1.bn.bias` size mismatch, should be 128, get 96
```

**Comment by haolongzhangm** [comment] 2022-08-02 04:58
which megengine commit  id you test?

**Comment by zoldaten** [comment] 2022-08-02 05:11
didnt catch. just `cd YOLOX ; git pull`

**Comment by haolongzhangm** [comment] 2022-08-02 05:14
MegEngine repo id;

**Comment by zoldaten** [comment] 2022-08-02 05:45
cd MegEngine
git reset --hard
HEAD is now at 58ba080d feat(x86/rvv): make gi conv algo adapt to vv and vf model
pi@raspberrypi:~/MegEngine $ git pull

but error the same:
```
Traceback (most recent call last):
  File "/home/pi/YOLOX/tools/export_mge.py", line 66, in <module>
    main(args, exp)
  File "/home/pi/YOLOX/tools/export_mge.py", line 59, in main
    model = build_and_load(model, args.ckpt)
  File "/home/pi/YOLOX/tools/export_mge.py", line 50, in build_and_load
    model.load_state_dict(model_weights, strict=False)
  File "/home/pi/.local/lib/python3.9/site-packages/megengine/module/module.py", line 550, in load_state_dict
    loaded, skipped = self._load_state_dict_with_closure(closure)
  File "/home/pi/.local/lib/python3.9/site-packages/megengine/module/module.py", line 604, in _load_state_dict_with_closure
    raise ValueError(
ValueError: param `backbone.C3_n3.conv1.bn.bias` size mismatch, should be 128, get 96
```

**Comment by haolongzhangm** [comment] 2022-08-02 05:51
just now, I test the latest id: 3b1101b5e9367dde7d8e6adc0a33d8868c766287

do not reproduction you issue

what`s more the test pkl md5 is:

80233d59135a7fa5d78db7aadcb88df8  yolox_tiny.pkl


now , I test the id you test  at  58ba080d5f7f9763cc74a07aadf8b2e20134901b   ...

**Comment by haolongzhangm** [comment] 2022-08-02 06:16
1: check you yolox_tiny.pkl md5 is  80233d59135a7fa5d78db7aadcb88df8
2: after you git pull in MegEngine , you need rebuild python whl to update code to whl file , then need reinstall whl package


or you can just debug(not create a whl file by : )
```
EXTRA_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RelWithDebInfo" scripts/cmake-build/host_build.sh -t
PYTHONPATH=you_megengine_repo_root/imperative/python:$PYTHONPATH python3 tools/export_mge.py -n yolox-tiny -c yolox_tiny.pkl --dump_path yolox_tiny.mge
```

**Comment by haolongzhangm** [comment] 2022-08-02 23:51
@zoldaten I also test the megengine id: https://github.com/MegEngine/MegEngine/commit/58ba080d5f7f9763cc74a07aadf8b2e20134901b  , which you report issue

also test pass:
* test command: cd YOLOX && PYTHONPATH=. python3.9 tools/export_mge.py -n yolox-tiny -c yolox_tiny.pkl --dump_path yolox_tiny.mge
*  yolox_tiny.pkl  MD5 is: 80233d59135a7fa5d78db7aadcb88df8
* megengine repo id: 58ba080d5f7f9763cc74a07aadf8b2e20134901b
* YOLOX repo id : 9e17c5d6beeedfa0544d24787a5f3383eebfae66

**Comment by haolongzhangm** [comment] 2022-08-02 23:55
also I upload the whl file at : 链接: https://pan.baidu.com/s/1s_mmAXDvXnoa8_lAl13Kjg?pwd=d9i3 提取码: d9i3 

which build from MegEngine repo id: https://github.com/MegEngine/MegEngine/commit/58ba080d5f7f9763cc74a07aadf8b2e20134901b

**Comment by haolongzhangm** [comment] 2022-08-03 11:22
HI  @zoldaten  
any update?

* as i test, it is ok at assign repo id,  u can sync my last two commented
* what is more, this issue topic is "Python whl package build on raspberry4b failed", and now already "fixed"

if you have more question about other use, you can create a new issue, so I will close this one , Thanks for you info

**Closed by haolongzhangm** 2022-08-03 11:23 UTC

**Comment by zoldaten** [comment] 2022-08-03 18:56
hi! 
i did:
- checked yolox_tiny.pkl MD5;
- git pulled Megengine and YOLOX;
- rebuilt wheels: 
./scripts/whl/manylinux2014/build_wheel_common.sh -sdk cpu
- reinstalled wheel:
pip3 install MegEngine-1.9999.0+cpu-cp39-cp39-manylinux2014_aarch64.whl --force-reinstall
 but error is the same:

```
Traceback (most recent call last):
  File "/home/pi/YOLOX/tools/export_mge.py", line 66, in <module>
    main(args, exp)
  File "/home/pi/YOLOX/tools/export_mge.py", line 59, in main
    model = build_and_load(model, args.ckpt)
  File "/home/pi/YOLOX/tools/export_mge.py", line 50, in build_and_load
    model.load_state_dict(model_weights, strict=False)
  File "/home/pi/.local/lib/python3.9/site-packages/megengine/module/module.py", line 550, in load_state_dict
    loaded, skipped = self._load_state_dict_with_closure(closure)
  File "/home/pi/.local/lib/python3.9/site-packages/megengine/module/module.py", line 604, in _load_state_dict_with_closure
    raise ValueError(
ValueError: param `backbone.C3_n3.conv1.bn.bias` size mismatch, should be 128, get 96
```

should i do:
git clean -xdf && git reset --hard && ./scripts/whl/manylinux2014/build_wheel_common.sh -sdk cpu
before rebuild ?

**Comment by haolongzhangm** [comment] 2022-08-04 00:54
just test the whl i prebuild at 链接: https://pan.baidu.com/s/1s_mmAXDvXnoa8_lAl13Kjg?pwd=d9i3 提取码: d9i3

**Comment by haolongzhangm** [comment] 2022-08-04 04:07
I find a raspberry4b , also test pass
```
➜  ~ /home/pi/.pyenv/versions/3.9.9/bin/python3 -m pip install MegEngine-1.9999.0+cpu-cp39-cp39-manylinux2014_aarch64.whl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing ./MegEngine-1.9999.0+cpu-cp39-cp39-manylinux2014_aarch64.whl
Requirement already satisfied: deprecated in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (1.2.13)
Requirement already satisfied: filelock in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (3.7.1)
Requirement already satisfied: mprop in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (0.16.0)
Requirement already satisfied: tqdm in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (4.64.0)
Requirement already satisfied: tabulate in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (0.8.10)
Requirement already satisfied: numpy>=1.18 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (1.23.1)
Requirement already satisfied: wheel in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (0.37.1)
Requirement already satisfied: requests in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (2.28.1)
Requirement already satisfied: pyarrow in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (9.0.0)
Requirement already satisfied: megfile>=0.0.10 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (1.0.0.post5)
Requirement already satisfied: opencv-python in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from MegEngine==1.9999.0+cpu) (4.6.0.66)
Requirement already satisfied: boto3 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from megfile>=0.0.10->MegEngine==1.9999.0+cpu) (1.24.45)
Requirement already satisfied: botocore>=1.13.0 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from megfile>=0.0.10->MegEngine==1.9999.0+cpu) (1.27.45)
Requirement already satisfied: smart-open>=1.6.0 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from megfile>=0.0.10->MegEngine==1.9999.0+cpu) (6.0.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from botocore>=1.13.0->megfile>=0.0.10->MegEngine==1.9999.0+cpu) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from botocore>=1.13.0->megfile>=0.0.10->MegEngine==1.9999.0+cpu) (1.26.11)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from botocore>=1.13.0->megfile>=0.0.10->MegEngine==1.9999.0+cpu) (1.0.1)
Requirement already satisfied: six>=1.5 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.13.0->megfile>=0.0.10->MegEngine==1.9999.0+cpu) (1.16.0)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from boto3->megfile>=0.0.10->MegEngine==1.9999.0+cpu) (0.6.0)
Requirement already satisfied: wrapt<2,>=1.10 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from deprecated->MegEngine==1.9999.0+cpu) (1.14.1)
Requirement already satisfied: charset-normalizer<3,>=2 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from requests->MegEngine==1.9999.0+cpu) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from requests->MegEngine==1.9999.0+cpu) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.9.9/lib/python3.9/site-packages (from requests->MegEngine==1.9999.0+cpu) (2022.6.15)
MegEngine is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/home/pi/.pyenv/versions/3.9.9/bin/python3 -m pip install --upgrade pip' command.



cd YOLOX
➜  YOLOX git:(main) ✗ git log -1 --format=%H |cat 
9e17c5d6beeedfa0544d24787a5f3383eebfae66


➜  YOLOX git:(main) ✗ md5sum yolox_tiny.pkl              
80233d59135a7fa5d78db7aadcb88df8  yolox_tiny.pkl


➜  YOLOX git:(main) ✗ PYTHONPATH=. /home/pi/.pyenv/versions/3.9.9/bin/python3 tools/export_mge.py -n yolox-tiny -c yolox_tiny.pkl --dump_path yolox_tiny.mge
➜  YOLOX git:(main) ✗ echo $?                                                                     
0


➜  YOLOX git:(main) ✗ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

```

**Comment by zoldaten** [comment] 2022-08-04 06:04
> just test the whl i prebuild at 链接: https://pan.baidu.com/s/1s_mmAXDvXnoa8_lAl13Kjg?pwd=d9i3 提取码: d9i3

cant reach there. perhaps, google drive ?

**Comment by zoldaten** [comment] 2022-08-05 13:55
reinstalled by you link provided but the error exists (
may be i missed something in install process.
may be that im on bullseye:
```
pi@raspberrypi:~/YOLOX $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by haolongzhangm** [comment] 2022-08-08 07:02
@zoldaten  It's really a strange thing


may casued by some python3 pip package version?
can you help test install the same version of pakcage ?

My test env pip package list and version is:
```
➜  ~ /home/pi/.pyenv/versions/3.9.9/bin/python3 -m pip list                                                              
Package            Version
------------------ ------------
boto3              1.24.45
botocore           1.27.45
certifi            2022.6.15
charset-normalizer 2.1.0
Deprecated         1.2.13
filelock           3.7.1
idna               3.3
jmespath           1.0.1
loguru             0.6.0
MegEngine          1.9999.0+cpu
megfile            1.0.0.post5
mprop              0.16.0
numpy              1.23.1
opencv-python      4.6.0.66
pip                21.2.4
pyarrow            9.0.0
python-dateutil    2.8.2
requests           2.28.1
s3transfer         0.6.0
setuptools         58.1.0
six                1.16.0
smart-open         6.0.0
tabulate           0.8.10
torch              1.12.0
tqdm               4.64.0
typing_extensions  4.3.0
urllib3            1.26.11
wheel              0.37.1
wrapt              1.14.1

```

**Comment by haolongzhangm** [comment] 2022-08-09 02:29
@zoldaten 
*  if you want to use python interface to inference， just follow https://github.com/MegEngine/YOLOX readme: "demo" to run with yolox_tiny.pkl, no need to use  yolox_tiny.mge
* if you want run interface with c++/c interface, will use yolox_tiny.mge , then follow, https://github.com/MegEngine/YOLOX/tree/main/demo/MegEngine/cpp
